version: '3.8'

services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    image: language-benchmark:latest
    container_name: benchmark-suite
    
    # Resource limits for consistent benchmarking
    deploy:
      resources:
        limits:
          cpus: '8.0'  # Adjust based on your cloud instance
          memory: 8G
        reservations:
          cpus: '4.0'
          memory: 4G
    
    # Environment variables
    environment:
      - BENCHMARK_MODE=full
      - DATA_SIZE=10000000
      - OUTPUT_FORMAT=json
      
    # Mount volumes for persistent results
    volumes:
      - ./results:/benchmark/results
      - ./logs:/benchmark/logs
      
    # Keep container running for interactive access
    stdin_open: true
    tty: true
    
    # Restart policy
    restart: unless-stopped
    
    # Networks
    networks:
      - benchmark-network

  # Optional: Results visualization service
  results-viewer:
    image: nginx:alpine
    container_name: benchmark-results
    ports:
      - "8080:80"
    volumes:
      - ./results:/usr/share/nginx/html/results:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - benchmark
    networks:
      - benchmark-network
    restart: unless-stopped

networks:
  benchmark-network:
    driver: bridge

volumes:
  benchmark-results:
    driver: local
  benchmark-logs:
    driver: local 